#ifndef SERIAL_SUIT_PROTOCOL_H
#define SERIAL_SUIT_PROTOCOL_H

#include "air_protocol.h"

enum
{
    SSP_FLASH_OK = 0,
    SSP_FLASH_WRONG_PARAM,
    SSP_FLASH_UNEXIST,
    SSP_FLASH_FAIL,
    SSP_FLASH_WRONG_ADDRESS,
    SSP_FLASH_VERIFY_FAIL,
    SSP_FLASH_WRONG_CRC_ADDRESS,
    SSP_FLASH_WRONG_FULL_LENGTH,
    SSP_FLASH_WRONG_CRC,
};

#endif // SERIAL_SUIT_PROTOCOL_H
