#ifndef SERIAL_SUIT_PROTOCOL_H
#define SERIAL_SUIT_PROTOCOL_H

enum
{
    SSP_CMD_DEBUG = 03,

    SSP_CMD_FLASH = 10,
    SSP_CMD_REBOOT,
};

enum
{
    SSP_FLASH_OK = 0,
    SSP_FLASH_WRONG_PARAM,
    SSP_FLASH_UNEXIST,
    SSP_FLASH_FAIL,
    SSP_FLASH_WRONG_ADDRESS,
    SSP_FLASH_VERIFY_FAIL,
};

#endif // SERIAL_SUIT_PROTOCOL_H
